apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vf7wc7bwh-nodejs
  janus-idp.io/tekton: vf7wc7bwh-nodejs
  backstage.io/kubernetes-id: vf7wc7bwh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vf7wc7bwh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
